# Generated by Django 2.2.3 on 2019-07-28 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanteLibApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SanteLibApp.Person')),
                ('preferred_languages', multiselectfield.db.fields.MultiSelectField(choices=[('FR', 'French'), ('EN', 'English'), ('AR', 'Arab')], default='FR', max_length=3)),
            ],
            bases=('SanteLibApp.person',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SanteLibApp.Person')),
                ('date_of_graduation', models.DateField(verbose_name='Date of graduation')),
                ('spoken_languages', multiselectfield.db.fields.MultiSelectField(choices=[('FR', 'French'), ('EN', 'English'), ('AR', 'Arab')], default='FR', max_length=8)),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('diploma', models.FileField(null=True, upload_to='diplomas/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('SanteLibApp.person',),
        ),
    ]
